version: '2.1'

networks:
  kong-net:
    name: kong-net-int

services:
  kong-migrations:
    image: kong/kong-gateway:2.8.4.10
    container_name: kong-ee-mig-int
    command: kong migrations bootstrap
    depends_on:
      db:
        condition: service_healthy
    environment:
      KONG_PASSWORD: password
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_CASSANDRA_CONTACT_POINTS: cassandra
      KONG_DB_UPDATE_PROPAGATION: 5
      KONG_DB_UPDATE_FREQUENCY: 10
      KONG_DATABASE: cassandra
      KONG_VAULTS: "off"
      CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT: 30000 
    networks:
      - kong-net
    restart: on-failure

  kong:
    image: kong/kong-gateway:2.8.4.10
    container_name: kong-ee-int
    user: "${KONG_USER:-kong}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_CASSANDRA_CONTACT_POINTS: cassandra
      KONG_DB_UPDATE_PROPAGATION: 5
      KONG_DB_UPDATE_FREQUENCY: 10
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT: 30000
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_PORTAL_GUI_LISTEN: 0.0.0.0:8003
      KONG_PORTAL_API_LISTEN: 0.0.0.0:8004
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_VITALS: "on"
      KONG_PORTAL: "on"
      KONG_ENFORCE_RBAC: "on"
      KONG_ADMIN_GUI_AUTH: "basic-auth"
      KONG_ADMIN_GUI_SESSION_CONF: '{ "cookie_name":"kong_manager_session", "secret":"set-your-string-here", "storage":"kong", "cookie_secure": false, "cookie_lifetime": 3600 }'
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
      KONG_ADMIN_API_URI: "http://localhost:8001"
      KONG_LOG_LEVEL: debug
      #keyring enabled
      # KONG_KEYRING_ENABLED: on
      # KONG_KEYRING_STRATEGY: cluster
      # KONG_KEYRING_PUBLIC_KEY: /certs/cert.pem
      # KONG_KEYRING_PRIVATE_KEY: /certs/key.pem
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8002:8002/tcp"
      - "8003:8003/tcp"
      - "8004:8004/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
      - "8445:8445/tcp"
      - "8446:8446/tcp"
      - "8447:8447/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

  db:
    image: cassandra:3
    container_name: cassandra
    restart: always
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 15s
        timeout: 10s
        retries: 10
    environment:
      CASSANDRA_CLUSTER_NAME: "KongCluster"
      CASSANDRA_NUM_TOKENS: "256"
      MAX_HEAP_SIZE: "512M"
      HEAP_NEWSIZE: "100M"
    networks:
      - kong-net    
    ports:
      - "9042:9042"     

  httpbin:
    container_name: httpbin-int
    image: "kennethreitz/httpbin"
    networks:
      - kong-net  
      
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: on-failure:10
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8201'
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8201'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    cap_add:
      - IPC_LOCK
    healthcheck:
      retries: 5
    networks:
      - kong-net      
    ports:
      - "8201:8201"