_format_version: "3.0"
# _workspace: test
services:
- connect_timeout: 60000
  enabled: true
  host: httpbin-1
  name: anything
  path: /anything
  plugins:
  - config:
      add:
        body: []
        headers:
        - '{vault://hcv/test_header/header-1}'
        json_types: []
        querystring: []
      allow:
        body: null
      append:
        body: []
        headers: []
        json_types: []
        querystring: []
      dots_in_keys: true
      http_method: null
      remove:
        body: []
        headers: []
        querystring: []
      rename:
        body: []
        headers: []
        querystring: []
      replace:
        body: []
        headers: []
        json_types: []
        querystring: []
        uri: null
    enabled: true
    name: request-transformer-advanced
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: anything
    path_handling: v0
    paths:
    - /anything
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
