version: "3.8"

services:
  node_app:
    image: node:16
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"  # Expose the application on port 3000
    environment:
      - PROVISION_KEY="Lvq5VoaXmix5NvN9obA9XF94Bbqaa0iS"  # Set your actual provision key
      - KONG_ADMIN=http://localhost:8001
      - KONG_API=http://localhost:8000
      - API_PATH=/mock
      - SERVICE_HOST=mockbin.org
      - SCOPES={"email":"Grant permissions to read your email address","address":"Grant permissions to read your address information","phone":"Grant permissions to read your mobile phone number"}
      - LISTEN_PORT=3000
    command: sh -c "npm install && node app.js"
