version: "3"

volumes:
    kong_data: {}

services:
  cassandra-dc1-seed:
    container_name: kong-ee-db-cassandra-dc1-seed-01
    restart: always
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 15s
        timeout: 10s
        retries: 10
    networks:
      - kong-ee
    image: cassandra:3-jammy
    ports:
      - "9042:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients
    environment:
      - CASSANDRA_SEEDS=kong-ee-db-cassandra-dc1-seed-01
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1

  cassandra-dc1-node-1:
    image: cassandra:3-jammy
    restart: on-failure
    container_name: kong-ee-db-cassandra-dc1-node-01
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 15s
        timeout: 10s
        retries: 10
    networks:
      - kong-ee
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=kong-ee-db-cassandra-dc1-seed-01
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    depends_on:
      cassandra-dc1-seed:
        condition: service_healthy

  cassandra-dc1-node-2:
    image: cassandra:3-jammy
    restart: on-failure
    container_name: kong-ee-db-cassandra-dc1-node-02
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 15s
        timeout: 10s
        retries: 10
    networks:
      - kong-ee
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=kong-ee-db-cassandra-dc1-seed-01
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    depends_on:
      cassandra-dc1-seed:
        condition: service_healthy

  kong-migrations:
    image: kong/kong-gateway:2.8.4.12-alpine
    container_name: kong-ee-migrations
    command: "kong migrations bootstrap && kong migrations up"
    depends_on:
      cassandra-dc1-node-2:
        condition: service_healthy 
    environment:
      KONG_PASSWORD: password
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_CASSANDRA_CONTACT_POINTS: cassandra-dc1-seed
      KONG_DB_UPDATE_PROPAGATION: 5
      KONG_DB_UPDATE_FREQUENCY: 10
      KONG_DATABASE: cassandra
      KONG_VAULTS: "off"
      CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT: 30000
    networks:
    - kong-ee
    restart: on-failure

  kong-ee:
    image: kong/kong-gateway:2.8.4.12-alpine
    #user: "${KONG_USER:-root}"
    container_name: kong-ee
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: bash    
    networks:
      - kong-ee
    depends_on:
        - kong-migrations
    restart: on-failure
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8002:8002/tcp"
      - "8003:8003/tcp"
      - "8004:8004/tcp"
      - "8100:8100/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
      - "8445:8445/tcp"
      - "9444:9411/tcp"
    environment:
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_STATUS_LISTEN: 0.0.0.0:8100
      KONG_CASSANDRA_CONTACT_POINTS: cassandra-dc1-seed
      KONG_DB_UPDATE_PROPAGATION: 5
      KONG_DB_UPDATE_FREQUENCY: 10
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT: 30000
      KONG_VAULTS: "off"
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_LOG_LEVEL: debug
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: bundled
      KONG_AUDIT_LOG: "off"
      #KONG_HEADERS: "off"
      KONG_ENFORCE_RBAC: "on"
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_SESSION_CONF: '{ "secret":"secret", "cookie_name":"kong_cookie", "cookie_secure":false }'
      KONG_PORTAL_EMAILS_FROM: noreply@konghq.com
      KONG_PORTAL_EMAILS_REPLY_TO: noreply@konghq.com
      KONG_PORTAL_AUTO_APPROVE: "on"
      KONG_SMTP_MOCK: "on"
      KONG_SMTP_HOST: smtp.gmail.com
      KONG_SMTP_PORT: 587
      KONG_SMTP_AUTH_TYPE: plain
      KONG_SMTP_STARTTLS: "on"
      KONG_SMTP_USERNAME: kongemailtest@gmail.com
      KONG_SMTP_PASSWORD: jNzjktjjzhzwYiQdpd2jymXV
      KONG_SMTP_ADMIN_EMAILS: noreply@konghq.com
      KONG_VITALS: "off"
#      KONG_NGINX_HTTP_PROXY_SSL_VERIFY: "on"
#      KONG_NGINX_HTTP_PROXY_SSL_VERIFY_DEPTH: 4
#      KONG_NGINX_HTTP_PROXY_SSL_TRUSTED_CERTIFICATE: /etc/ssl/cert.pem
      KONG_TRUSTED_IPS: 0.0.0.0/0,::/0

#This is where the portal config is
      KONG_PORTAL: "on"
      KONG_PORTAL_GUI_LISTEN: 0.0.0.0:8003
      KONG_PORTAL_GUI_HOST: localhost:8003

#Configure cluster cert
      KONG_CLUSTER_CERT: /certs/cluster.crt
      KONG_CLUSTER_CERT_KEY: /certs/cluster.key

      KONG_KEYRING_ENABLED: on
      KONG_KEYRING_STRATEGY: cluster
      KONG_KEYRING_PUBLIC_KEY: /certs/cert.pem
      KONG_KEYRING_PRIVATE_KEY: /certs/key.pem
    
    volumes:
      - ./certs:/certs
networks:
    kong-ee:
