# Original configuration with additions for ingress support

apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-dp-config
  namespace: kong
data:
  # Configuration specific to the Kong data plane
  kong.conf: |
    database = off
    role = data_plane
    cluster_control_plane = kong-cp-kong-cluster.kong.svc.cluster.local:8005
    cluster_telemetry_endpoint = kong-cp-kong-clustertelemetry.kong.svc.cluster.local:8006
    lua_ssl_trusted_certificate = /etc/secrets/kong-cluster-cert/tls.crt
    cluster_cert = /etc/secrets/kong-cluster-cert/tls.crt
    cluster_cert_key = /etc/secrets/kong-cluster-cert/tls.key

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-dp
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-dp
  template:
    metadata:
      labels:
        app: kong-dp
    spec:
      containers:
      - name: kong-dp
        image: kong/kong-gateway:3.7.1.1
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_ROLE
          value: "data_plane"
        - name: KONG_CLUSTER_CONTROL_PLANE
          value: "kong-cp-kong-cluster.kong.svc.cluster.local:8005"
        - name: KONG_CLUSTER_TELEMETRY_ENDPOINT
          value: "kong-cp-kong-clustertelemetry.kong.svc.cluster.local:8006"
        - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
          value: "/etc/secrets/kong-cluster-cert/tls.crt"
        - name: KONG_CLUSTER_CERT
          value: "/etc/secrets/kong-cluster-cert/tls.crt"
        - name: KONG_CLUSTER_CERT_KEY
          value: "/etc/secrets/kong-cluster-cert/tls.key"
        volumeMounts:
        - name: kong-cluster-cert
          mountPath: /etc/secrets/kong-cluster-cert
          readOnly: true
      volumes:
      - name: kong-cluster-cert
        secret:
          secretName: kong-cluster-cert

---

apiVersion: v1
kind: Service
metadata:
  name: kong-dp
  namespace: kong
spec:
  type: ClusterIP
  selector:
    app: kong-dp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  - protocol: TCP
    port: 8443
    targetPort: 8443

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-dp-ingress
  namespace: kong
  annotations:
    # Replace with your ingress controller's specific annotations if needed
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kong.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kong-dp
            port:
              number: 8000
  tls:
  - hosts:
    - kong.your-domain.com
    secretName: kong-tls
